#spring.datasource.url=jdbc:mysql://localhost:3306/fracas_scr?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=Railbit@24
#server.port=8540



spring.datasource.url=jdbc:mysql://213.199.57.172:3306/unms_ncr?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=satYamQazwsx@321
server.port=8530